import { app, dialog } from 'electron';
import * as path from 'path';
import * as fs from 'fs';
import { spawn } from 'child_process';

/* ---------------------------------------------------------------------------
 * Database lifecycle for the packaged app.
 *
 * Once shipped, the user's app.db is the only copy of their org — their roles,
 * teams, memory and run history — and we cannot reach it again. So every schema
 * change has to be applied in place, on their machine, without losing data:
 *
 *   1. copy the bundled template database on first launch
 *   2. back it up before touching it on every later launch
 *   3. run `prisma migrate deploy`
 *   4. seed the shipped floors, roles and cast (idempotent)
 *   5. on failure, restore the backup and refuse to start
 *
 * Migrations MUST be additive (new tables, new nullable columns). Drops, renames
 * and type changes need an explicit copy-and-backfill migration — there is no
 * rollback path once a build is in a user's hands.
 *
 * THE TEMPLATE IS BUILD OUTPUT. backend/database/seed.db is generated by
 * `npm run seed:db` (scripts/buildSeedDb.js) from the migrations plus the seed
 * script, never hand-maintained — so it cannot carry the development database's
 * threads, messages or run history.
 * ------------------------------------------------------------------------- */

/** Resolve a path inside the packaged app that is NOT in the asar archive.
 *  `asarUnpack` mirrors those files into app.asar.unpacked/, so a real path
 *  exists for anything the OS must read or exec. */
function unpacked(...segments: string[]): string {
  return path.join(app.getAppPath().replace(/app\.asar$/, 'app.asar.unpacked'), ...segments);
}

/** Resolve a path under resources/, where `extraResources` copies files.
 *
 *  backend/node_modules lives HERE rather than in app.asar.unpacked, because
 *  electron-builder prunes node_modules out of `files` entirely (see the comment
 *  in electron-builder.yml). Getting this wrong is what produced
 *  "prisma not found at ...pp.asar.unpackedackend
ode_modules\..." on the
 *  first packaged launch. */
function resource(...segments: string[]): string {
  return path.join(process.resourcesPath, ...segments);
}

function dbPaths() {
  // `app.db`, not `dev.db`: on the user's machine this is THEIR database, not a
  // development one. The bundled template is seed.db and is copied to this path.
  // Matches backend/paths.ts: DATA_ROOT = APP_USER_DATA, and the database lives
  // in `database/` beneath it. Both processes must agree on this path.
  const dir = path.join(app.getPath('userData'), 'database');
  return { dir, db: path.join(dir, 'app.db') };
}

/** Prisma wants a file: URL with forward slashes, even on Windows. */
function databaseUrl(dbPath: string): string {
  return `file:${dbPath.replace(/\\/g, '/')}`;
}

/** The DATABASE_URL the backend and every Prisma invocation must share. */
export function packagedDatabaseUrl(): string {
  return databaseUrl(dbPaths().db);
}

/**
 * Run a Node script from the packaged backend as a child process.
 *
 * `process.execPath` is the Electron binary; ELECTRON_RUN_AS_NODE makes it
 * behave as plain Node, which is the same trick the backend spawn uses — so we
 * never bundle a second Node runtime.
 */
function runNode(script: string, args: string[], dbPath: string, label: string): Promise<void> {
  return new Promise((resolve, reject) => {
    if (!fs.existsSync(script)) {
      reject(new Error(`${label} not found at ${script}`));
      return;
    }

    const child = spawn(process.execPath, [script, ...args], {
      // The backend's dependencies live under resources/, not beside the scripts
      // in app.asar.unpacked, so Node's own resolution from the script's folder
      // would find nothing. Running FROM resources/backend makes `require` walk
      // up into the node_modules that is actually there.
      cwd: resource('backend'),
      env: {
        ...process.env,
        ELECTRON_RUN_AS_NODE: '1',
        // Belt and braces: NODE_PATH covers a script that resolves from its own
        // directory rather than the cwd.
        NODE_PATH: resource('backend', 'node_modules'),
        DATABASE_URL: databaseUrl(dbPath),
        APP_USER_DATA: app.getPath('userData'),
        // Suppress the CLI's "update available" banner — it writes box-drawing
        // characters to stdout and clutters the log.
        CHECKPOINT_DISABLE: '1',
      },
      stdio: ['ignore', 'pipe', 'pipe'],
    });

    let stderr = '';
    child.stdout?.on('data', (d: Buffer) => console.log(`[${label}] ${d.toString().trimEnd()}`));
    child.stderr?.on('data', (d: Buffer) => {
      stderr += d.toString();
      console.error(`[${label}] ${d.toString().trimEnd()}`);
    });

    child.on('error', reject);
    child.on('close', (code) =>
      code === 0
        ? resolve()
        : reject(new Error(`${label} exited with code ${code}\n${stderr}`))
    );
  });
}

/** Run the Prisma CLI. The schema is passed explicitly because Prisma resolves
 *  migrations/ relative to it, and both must be the unpacked copies. */
function runPrisma(args: string[], dbPath: string): Promise<void> {
  const schema = unpacked('backend', 'prisma', 'schema.prisma');
  if (!fs.existsSync(schema)) {
    return Promise.reject(new Error(`Prisma schema not found at ${schema}`));
  }
  const cli = resource('backend', 'node_modules', 'prisma', 'build', 'index.js');
  return runNode(cli, [...args, '--schema', schema], dbPath, 'prisma');
}

/**
 * Prepare the user's database: create, back up, migrate, seed.
 * Resolves when the database is safe for the backend to open.
 * Throws only after restoring the pre-migration backup.
 */
export async function prepareDatabase(): Promise<void> {
  // Development runs against backend/database/dev.db and is managed by hand with
  // `prisma migrate dev` — nothing to do here.
  if (!app.isPackaged) return;

  const { dir, db } = dbPaths();
  fs.mkdirSync(dir, { recursive: true });

  // --- First launch: copy the bundled template ----------------------------
  // The template already has the schema, the floors, the role library and the
  // cast, so first launch is a file copy rather than 26 migrations plus a seed.
  const firstRun = !fs.existsSync(db);
  if (firstRun) {
    // Unpacked, because fs reads a real path — a file inside the asar archive
    // is visible to require() but not to copyFileSync.
    const template = unpacked('backend', 'database', 'seed.db');
    if (!fs.existsSync(template)) {
      throw new Error(`Template database missing from the bundle at ${template}`);
    }
    fs.copyFileSync(template, db);
    console.log(`[db] created from template at ${db}`);
  }

  // --- Back up before touching an existing database ------------------------
  // Keyed by version so an upgrade never overwrites the previous version's
  // safety net, and re-running the same version is idempotent.
  const backup = path.join(dir, `app.db.bak-${app.getVersion()}`);
  let backedUp = false;
  if (!firstRun && !fs.existsSync(backup)) {
    fs.copyFileSync(db, backup);
    backedUp = true;
    console.log(`[db] backed up to ${backup}`);
  }

  try {
    // --- Apply migrations --------------------------------------------------
    // The template carries its own _prisma_migrations history (it was built by
    // the same migrations), so `deploy` is a no-op on first launch and applies
    // only what is genuinely pending on later upgrades. No baseline step is
    // needed for the same reason.
    await runPrisma(['migrate', 'deploy'], db);
    console.log('[db] migrations up to date');

    // --- Seed ---------------------------------------------------------------
    // The shipped floors, the role library and the cast. Idempotent: it upserts
    // by stable keys, so it is safe on every launch, not just the first. Running
    // it on upgrades too is deliberate — a new release that adds a floor or a
    // role gets it without the user reinstalling.
    await runNode(unpacked('backend', 'dist', 'prisma', 'seed.js'), [], db, 'seed');
  } catch (err) {
    // --- Restore and refuse to start ---------------------------------------
    // A half-migrated database that silently starts is worse than an app that
    // will not open: the user keeps writing into a broken schema.
    const message = err instanceof Error ? err.message : String(err);
    console.error('[db] preparation failed:', message);

    if (backedUp && fs.existsSync(backup)) {
      try {
        fs.copyFileSync(backup, db);
        console.log('[db] restored pre-migration backup');
      } catch (restoreErr) {
        console.error('[db] restore failed:', restoreErr);
      }
    } else if (firstRun && fs.existsSync(db)) {
      // A failed FIRST run leaves a half-built database with no backup to fall
      // back on. Removing it means the next launch retries cleanly instead of
      // tripping over the wreckage.
      try {
        fs.rmSync(db, { force: true });
        console.log('[db] removed partially created database');
      } catch {
        /* best effort */
      }
    }

    dialog.showErrorBox(
      'Sanctorum could not prepare its database',
      'The database could not be set up for this version of Sanctorum, so the ' +
        'app has stopped rather than risk damaging your work.\n\n' +
        (backedUp
          ? `Your data is safe and has been restored from a backup at:\n${backup}\n\n`
          : '') +
        `Details: ${message}`
    );

    throw err;
  }
}

export default prepareDatabase;
