// GENERATED by scripts/scanTiles.mjs — do not edit by hand.
// Every tile here can be painted in the editor. Tiles are cosmetic and never
// block movement (the collision grid is separate). To add art, drop PNGs into a
// folder under public/assets/floor/tiles/ (each folder is a palette group; each
// image is a variation) and re-run the scan (it runs on `npm run dev` and
// `npm run build`).

/** A paintable, cosmetic tile. `group` is its palette section; `variant` is
 *  the variation number (1..N) or null for a single-image tile. */
export type TileKindDef = {
  key: string;
  label: string;
  group: string;
  variant: number | null;
  path: string;
};

export const TILE_KINDS: readonly TileKindDef[] = [
  {
    key: "acid",
    label: "Acid",
    group: "Tiles",
    variant: null,
    path: "/assets/floor/tiles/acid.png",
  },
  {
    key: "brick_black",
    label: "Brick black",
    group: "Tiles",
    variant: null,
    path: "/assets/floor/tiles/brick_black.png",
  },
  {
    key: "brick_red",
    label: "Brick red",
    group: "Tiles",
    variant: null,
    path: "/assets/floor/tiles/brick_red.png",
  },
  {
    key: "brick_stone",
    label: "Brick stone",
    group: "Tiles",
    variant: null,
    path: "/assets/floor/tiles/brick_stone.png",
  },
  {
    key: "carpet_red",
    label: "Red carpet",
    group: "Tiles",
    variant: null,
    path: "/assets/floor/tiles/carpet_red.png",
  },
  {
    key: "clear_water_1",
    label: "Clear water 1",
    group: "Tiles",
    variant: 1,
    path: "/assets/floor/tiles/clear_water_1.png",
  },
  {
    key: "desert_1",
    label: "Desert 1",
    group: "Tiles",
    variant: 1,
    path: "/assets/floor/tiles/desert_1.png",
  },
  {
    key: "dirt_1",
    label: "Dirt 1",
    group: "Tiles",
    variant: 1,
    path: "/assets/floor/tiles/dirt_1.png",
  },
  {
    key: "floor_white",
    label: "White floor",
    group: "Tiles",
    variant: null,
    path: "/assets/floor/tiles/floor_white.png",
  },
  {
    key: "glacier_1",
    label: "Glacier 1",
    group: "Tiles",
    variant: 1,
    path: "/assets/floor/tiles/glacier_1.png",
  },
  {
    key: "grass_1",
    label: "Grass 1",
    group: "Tiles",
    variant: 1,
    path: "/assets/floor/tiles/grass_1.png",
  },
  {
    key: "ice_1",
    label: "Ice 1",
    group: "Tiles",
    variant: 1,
    path: "/assets/floor/tiles/ice_1.png",
  },
  {
    key: "jungle_1",
    label: "Jungle 1",
    group: "Tiles",
    variant: 1,
    path: "/assets/floor/tiles/jungle_1.png",
  },
  {
    key: "lava_1",
    label: "Lava 1",
    group: "Tiles",
    variant: 1,
    path: "/assets/floor/tiles/lava_1.png",
  },
  {
    key: "lava_2",
    label: "Lava 2",
    group: "Tiles",
    variant: 2,
    path: "/assets/floor/tiles/lava_2.png",
  },
  {
    key: "marble_1",
    label: "Marble 1",
    group: "Tiles",
    variant: 1,
    path: "/assets/floor/tiles/marble_1.png",
  },
  {
    key: "metal_!",
    label: "Metal",
    group: "Tiles",
    variant: null,
    path: "/assets/floor/tiles/metal_!.png",
  },
  {
    key: "purple",
    label: "Purple",
    group: "Tiles",
    variant: null,
    path: "/assets/floor/tiles/purple.png",
  },
  {
    key: "runestone_1",
    label: "Runestone 1",
    group: "Tiles",
    variant: 1,
    path: "/assets/floor/tiles/runestone_1.png",
  },
  {
    key: "sand_1",
    label: "Sand 1",
    group: "Tiles",
    variant: 1,
    path: "/assets/floor/tiles/sand_1.png",
  },
  {
    key: "snow_1",
    label: "Snow 1",
    group: "Tiles",
    variant: 1,
    path: "/assets/floor/tiles/snow_1.png",
  },
  {
    key: "stone_1",
    label: "Stone 1",
    group: "Tiles",
    variant: 1,
    path: "/assets/floor/tiles/stone_1.png",
  },
  {
    key: "swamp_1",
    label: "Swamp 1",
    group: "Tiles",
    variant: 1,
    path: "/assets/floor/tiles/swamp_1.png",
  },
  {
    key: "toxic_1",
    label: "Toxic 1",
    group: "Tiles",
    variant: 1,
    path: "/assets/floor/tiles/toxic_1.png",
  },
  {
    key: "void_1",
    label: "Void 1",
    group: "Tiles",
    variant: 1,
    path: "/assets/floor/tiles/void_1.png",
  },
  {
    key: "wall_blue",
    label: "Blue panel",
    group: "Tiles",
    variant: null,
    path: "/assets/floor/tiles/wall_blue.png",
  },
  {
    key: "water_1",
    label: "Water 1",
    group: "Tiles",
    variant: 1,
    path: "/assets/floor/tiles/water_1.png",
  },
  {
    key: "white_1",
    label: "White 1",
    group: "Tiles",
    variant: 1,
    path: "/assets/floor/tiles/white_1.png",
  },
  {
    key: "wood_1",
    label: "Wood 1",
    group: "Tiles",
    variant: 1,
    path: "/assets/floor/tiles/wood_1.png",
  },
  {
    key: "wood_2",
    label: "Wood 2",
    group: "Tiles",
    variant: 2,
    path: "/assets/floor/tiles/wood_2.png",
  },
  {
    key: "wood_3",
    label: "Wood 3",
    group: "Tiles",
    variant: 3,
    path: "/assets/floor/tiles/wood_3.png",
  },
];

/** Palette group names, in display order. */
export const TILE_GROUPS: readonly string[] = ["Tiles"];
