import { PROP_KINDS, PROP_GROUPS, type PropKind } from './props.generated';
import { TILE_KINDS, TILE_GROUPS, type TileKindDef } from './tiles.generated';

/**
 * The tile kinds that can be painted. The list is generated by
 * scripts/scanTiles.mjs from the PNGs under public/assets/floor/tiles/, so
 * dropping in new art and re-running the scan (it runs on `npm run dev` and
 * `npm run build`) makes it paintable.
 */
export { TILE_KINDS, TILE_GROUPS };
export type { TileKindDef };

/** A tile's key is a free-form string now (variations make it dynamic). */
export type TileKind = string;

export const tilePath = (kind: string): string | undefined =>
  TILE_KINDS.find((t) => t.key === kind)?.path;

/** Tiles in a palette group, in file order. */
export const tilesInGroup = (group: string): readonly TileKindDef[] =>
  TILE_KINDS.filter((t) => t.group === group);

/**
 * Props that can be placed. These block a tile — an agent cannot walk through
 * them. `foot` is the draw box (props overhang their cell), in world px.
 *
 * The list is generated by scripts/scanProps.mjs from the PNGs under
 * public/assets/floor/objects/, so dropping in new art and re-running the scan
 * (it runs on `npm run dev` and `npm run build`) makes it placeable.
 */
export { PROP_KINDS, PROP_GROUPS };
export type { PropKind };

/** A prop's key is a free-form string now (variations make it dynamic). */
export type PropKindKey = string;

export const propDef = (kind: string) => PROP_KINDS.find((p) => p.key === kind);

/** Props in a palette group, in file order. */
export const propsInGroup = (group: string): readonly PropKind[] =>
  PROP_KINDS.filter((p) => p.group === group);

/** Editor tools. `select` is the normal play mode; the others edit. The `seat`
 *  tool places desks; `block` paints invisible collision onto the grid; `erase`
 *  removes tiles, props, or seats at a cell. */
export type EditorTool = 'select' | 'tile' | 'prop' | 'seat' | 'block' | 'erase';

export type Rotation = 0 | 90 | 180 | 270;

export const ROTATIONS: Rotation[] = [0, 90, 180, 270];

/** Next quarter-turn, wrapping at 360. */
export const nextRotation = (r: Rotation): Rotation =>
  ROTATIONS[(ROTATIONS.indexOf(r) + 1) % ROTATIONS.length];
