// Auto-discovers paintable tiles from public/assets/floor/tiles/ and writes a
// generated TILE_KINDS array, grouped for the palette. Runs before `dev` and
// `build`.
//
// Conventions (mirrors scanProps.mjs):
//   - One level deep: tiles/<category>/<image>.png. Each folder is a palette
//     GROUP, and EVERY image in it is its own paintable tile (a variation).
//   - Loose top-level PNGs fall into a temporary "Tiles" group, so nothing
//     breaks while art is being moved into category folders.
//   - Tiles are cosmetic (they do not block movement — the collision grid is
//     separate), so there is no foot box or blocking flag.
//   - FILE_KEY pins canonical keys for art whose filename differs from the
//     `kind` stored in the DB, matched by filename base.

import { promises as fs } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '..');
const TILES_DIR = path.join(ROOT, 'public/assets/floor/tiles');
const OUT_FILE = path.join(ROOT, 'lib/office/editor/tiles.generated.ts');
const URL_PREFIX = '/assets/floor/tiles';

// The group loose top-level files land in until they are moved into a folder.
const LOOSE_GROUP = 'Tiles';

// Canonical keys/labels for tiles referenced by the seed / existing floors, so
// their painted tiles keep resolving even if the filename is awkward. Matched by
// filename base (no extension). The three original tiles are the seeded ones.
const FILE_KEY = {
  floor_white: { key: 'floor_white', label: 'White floor' },
  carpet_red: { key: 'carpet_red', label: 'Red carpet' },
  wall_blue: { key: 'wall_blue', label: 'Blue panel' },
};

const isPng = (name) => name.toLowerCase().endsWith('.png');
const base = (file) => file.replace(/\.png$/i, '');

/** "brick_black" -> "Brick black"; "grass_!" -> "Grass". */
function titleCase(name) {
  const words = name.replace(/[_!-]+/g, ' ').trim().split(/\s+/).filter(Boolean);
  if (words.length === 0) return name;
  return words[0].charAt(0).toUpperCase() + words[0].slice(1) + (words.length > 1 ? ' ' + words.slice(1).join(' ') : '');
}

/** The variation number from a "..._N" filename, or null if it has none. */
function variantOf(fileBase) {
  const m = fileBase.match(/_(\d+)$/);
  return m ? Number(m[1]) : null;
}

/** Builds one tile record from a file's base name, its URL, and its group.
 *  `inFolder` picks the label style: inside a category folder a numbered file
 *  shows just its number (the header carries the name); a loose file shows its
 *  full name, so the transition "Tiles" group stays readable. */
function tileFrom(fileBase, url, group, inFolder) {
  const mapped = FILE_KEY[fileBase];
  const variant = variantOf(fileBase);
  const label =
    mapped?.label ?? (inFolder && variant !== null ? String(variant) : titleCase(fileBase));
  return { key: mapped?.key ?? fileBase, label, group, variant, path: url };
}

async function scan() {
  const entries = await fs.readdir(TILES_DIR, { withFileTypes: true });
  const tiles = [];

  for (const entry of entries) {
    if (entry.isDirectory()) {
      const folder = entry.name;
      const group = titleCase(folder);
      const files = (await fs.readdir(path.join(TILES_DIR, folder))).filter(isPng).sort();
      for (const file of files) {
        tiles.push(tileFrom(base(file), `${URL_PREFIX}/${folder}/${file}`, group, true));
      }
    } else if (entry.isFile() && isPng(entry.name)) {
      tiles.push(tileFrom(base(entry.name), `${URL_PREFIX}/${entry.name}`, LOOSE_GROUP, false));
    }
  }

  return tiles;
}

/** Groups in display order: the loose "Tiles" group last, folders A→Z. */
function groupOrder(tiles) {
  const names = [...new Set(tiles.map((t) => t.group))];
  return names.sort((a, b) => {
    if (a === LOOSE_GROUP) return 1;
    if (b === LOOSE_GROUP) return -1;
    return a.localeCompare(b);
  });
}

function serialize(tiles) {
  const order = groupOrder(tiles);
  const body = tiles
    .map(
      (t) =>
        `  {\n    key: ${JSON.stringify(t.key)},\n    label: ${JSON.stringify(
          t.label
        )},\n    group: ${JSON.stringify(t.group)},\n    variant: ${
          t.variant === null ? 'null' : t.variant
        },\n    path: ${JSON.stringify(t.path)},\n  },`
    )
    .join('\n');

  return `// GENERATED by scripts/scanTiles.mjs — do not edit by hand.
// Every tile here can be painted in the editor. Tiles are cosmetic and never
// block movement (the collision grid is separate). To add art, drop PNGs into a
// folder under public/assets/floor/tiles/ (each folder is a palette group; each
// image is a variation) and re-run the scan (it runs on \`npm run dev\` and
// \`npm run build\`).

/** A paintable, cosmetic tile. \`group\` is its palette section; \`variant\` is
 *  the variation number (1..N) or null for a single-image tile. */
export type TileKindDef = {
  key: string;
  label: string;
  group: string;
  variant: number | null;
  path: string;
};

export const TILE_KINDS: readonly TileKindDef[] = [
${body}
];

/** Palette group names, in display order. */
export const TILE_GROUPS: readonly string[] = ${JSON.stringify(order)};
`;
}

async function main() {
  const tiles = await scan();
  await fs.writeFile(OUT_FILE, serialize(tiles), 'utf8');
  console.log(`scanTiles: wrote ${tiles.length} tiles in ${new Set(tiles.map((t) => t.group)).size} groups`);
}

main().catch((err) => {
  console.error('scanTiles failed:', err);
  process.exit(1);
});
